### ISSUE TITLE
Important: Buildserver uses wrong compile flags. -march=native optimizes and targets CPU specific instructions 

### ISSUE THREAD

**Issue by X4** [Antergos/antbs#3]
Hi,

I've started debugging a little why `zfs list` and `zpool list` were throwing errors for me.
See here: https://github.com/zfsonlinux/zfs/issues/4407

No I'm coming to the conclusion that the Anergos Build-Farm is using the GCC Flag `-march=native`, when it should be `-march=x86-64`. However using this flag at all is superficial, because the `./configure` step already detects the target platform correctly, thus making native CPU instruction optimizations dangerous and generally wrong. I'm sure a few other bug reports, crashes, segfaults etc. will vanish when you stop using this flag.

Just replace `-march=native` with `-march=x86-64` in L104-105 and everywhere else accordingly in the Build-Farm (Jenkins). 
https://github.com/Antergos/antbs/blob/master/antbs/build/build.sh#L104

**Comment by karasu** [comment]
@lots0logs : Check this out, please. Some users have complained about it (zfs list not working).

Cheers!

**Comment by lots0logs** [comment]
> No I'm coming to the conclusion that the Anergos Build-Farm is using the GCC Flag -march=native, when it should be -march=x86-64. However using this flag at all is superficial, because the ./configure step already detects the target platform correctly, thus making native CPU instruction optimizations dangerous and generally wrong. I'm sure a few other bug reports, crashes, segfaults etc. will vanish when you stop using this flag.

@X4 Do you have any reference links to back up these claims?

**Comment by X4** [comment]
Hi @lots0logs,

here's a [reference from the GCC Manual](https://gcc.gnu.org/onlinedocs/gcc-4.3.2//gcc/i386-and-x86_002d64-Options.html#i386-and-x86_002d64-Options). If you refer to the claim of software that's broken, because of this optimization on CPUs not supporting ie. your CPU's Advanced Vector Extensions (AVX) instruction set, then should check out the problems arising with package-query and zfs-utils in example. If you debug this using `gdb` on `QEMU` or a physical CPU that has not AVX support, you will be able replicate these issues yourself.

**In summary:**
> **native**
>     This selects the CPU to tune for at compilation time by determining the processor type of the compiling machine. Using `-mtune=native` will produce code optimized for the local machine under the constraints of the selected instruction set. Using `-march=native` will enable all instruction subsets supported by the local machine (hence the result might not run on different machines). 

As mentioned earlier, the corresponding line that [optimizes for the local CPU's native instruction set is in used in your build farm](https://github.com/Antergos/antbs/blob/master/antbs/build/build.sh#L104). 

Can you initiate a rebuild of all packages on your build farm without the `native` optimization flag, please?

**Comment by X4** [comment]
You can read these two [**1**](http://stackoverflow.com/a/10134204), [**2**](http://stackoverflow.com/a/28205379) StackOverflow top posts on `-march`, but if you want to go deeper into the issue I recommend reading the Gentoo Wiki on [GCC Optimization](https://wiki.gentoo.org/wiki/GCC_optimization#Ready.3F) and [CFLAGS](https://wiki.gentoo.org/wiki/CFLAGS).

To see command-line flags, use:
* `gcc -march=native -E -v - </dev/null 2>&1 | grep cc1`

The following will strip the unnecessary `-mno` flags:
* `gcc -march=native -v -E - < /dev/null 2>&1 | grep cc1 | perl -pe 's/ -mno-\S+//g; s/^.* - //g;'`

**Comment by lots0logs** [comment]
Thanks. I will review the information asap. Provided that it all checks out then I will make the change on our server. In which case I hope you will consider updating the makepkg page on the Arch Wiki with the information :smile:

**Comment by X4** [comment]
You mean: https://wiki.archlinux.org/index.php/makepkg?
What information should I include there?

It clearly says: 
> As of version 4.3.0, GCC can automatically detect and enable safe architecture-specific optimizations. To use this feature, first remove any -march and -mtune flags, then add -march=native. 
That means on your LOCAL machine, such tuning is recommended. But if you're building packages for a wide array of x86-64 CPU models, then local CPU specific optimizations should generally be avoided.

**Comment by lots0logs** [comment]
I think it could be a bit clearer about building packages for your local machine vs building packages for other machines. Anyway, I can update it if I have time (and if I remember :grimacing: )

**Comment by X4** [comment]
Thank you very much! Would you mind informing me, when you toss a new rebuild of all packages? Because until then I'll have to live with a **SIGIL (core dumped)** for various Antergos packages, which is unpleasing situation.

**Comment by X4** [comment]
I'm not registered in your forum, but have looked if SIGIL errors happen to others too.

Here's the result for your information:
* https://forum.antergos.com/topic/4150/update-breaks-pacman-for-me-again/3
* https://forum.antergos.com/topic/4128/yaourt-core-dump/2
* https://forum.antergos.com/topic/4040/zfs-zpool-invalid-instruction/6
* https://forum.antergos.com/topic/4064/zfs-mirror-install-in-vm-cannot-open-zroot-no-such-pool/3
* https://forum.antergos.com/topic/4064/zfs-mirror-install-in-vm-cannot-open-zroot-no-such-pool/3

**Comment by axaxs** [comment]
sorry for being late to the party.  X4 is right, march flag should -not- be
used for distributed binaries as it builds specific to the local machine
only.
