### ISSUE TITLE
500 Internal Server Error - Unable to login @ https://build.antergos.com/auth/login

### ISSUE THREAD

**Issue by CurtisBelt** [Antergos/antbs#87]
Maybe this is for authorized people only, I don't actually know what's available once you login here :) Just trying to learn if or how I can use it. Thanks!

![screenshot_1](https://user-images.githubusercontent.com/4251760/38093820-b6a24162-3331-11e8-9ce5-b114f26cef22.png)
![screenshot_2](https://user-images.githubusercontent.com/4251760/38093821-b6afb5d6-3331-11e8-9aed-f146c4978d70.png)

**Comment by lots0logs** [comment]
The build server is not for public use. Only members of our dev team have access to log in.
